apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character
  template:
    metadata:
      labels:
        app: character
    spec:
      containers:
        - name: character
          image: dungeon-logger/character
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: dungeon-logger
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: MONGO_URI
              value: "mongodb://character-mongo-srv:27017/character"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: character-srv
spec:
  selector:
    app: character
  type: LoadBalancer
  ports:
    - name: character
      protocol: TCP
      port: 3000
      targetPort: 3000
